export const ADD_SYMPTOM = "ADD_SYMPTOM";
export const ADD_SYMPTOM_SUCCESS = "ADD_SYMPTOM_SUCCESS";

export const DELETE_SYMPTOM = "DELETE_SYMPTOM";
export const DELETE_SYMPTOM_SUCCESS = "DELETE_SYMPTOM_SUCCESS";

export const EDIT_SYMPTOM = "EDIT_SYMPTOM";
export const EDIT_SYMPTOM_SUCCESS = "EDIT_SYMPTOM_SUCCESS";

export const GET_SYMPTOMS = "GET_SYMPTOMS";
export const GET_SYMPTOMS_SUCCESS = "GET_SYMPTOMS_SUCCESS";

export const SET_SYMPTOMS_DATE_RANGE = "SET_SYMPTOMS_DATE_RANGE";

export const REQUEST_ERR = "REQUEST_ERR";
