export const ADD_MEAL = "ADD_MEAL"
export const ADD_MEAL_SUCCESS = "ADD_MEAL_SUCCESS"

export const DELETE_MEAL = "DELETE_MEAL"
export const DELETE_MEAL_SUCCESS = "DELETE_MEAL_SUCCESS"

export const UPDATE_MEAL = "UPDATE_MEAL"
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS"

export const GET_MEALS = "GET_MEALS"
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS"

export const REQUEST_ERR = "REQUEST_ERR"