env: standard
runtime: nodejs14
service: default

handlers:
   - url: /api/.*
     script: auto
   - url: .*/favicon.png
     static_files: public/favicon.png
     upload: public/favicon.png
   - url: /static
     static_dir: public/static
   - url: /(.*\.(json|ico|js))$
     static_files: public/\1
     upload: public/.*\.(json|ico|js)$
   - url: .*
     static_files: public/index.html
     upload: public/index.html
     secure: always
     redirect_http_response_code: 301
