runtime: nodejs
env: flex

manual_scaling:
   instances: 1

resources:
   cpu: 2
   memory_gb: 2.3
   disk_size_gb: 10

handlers:
   - url: /
     static_files: public/index.html
     upload: public/index.html
   - url: /
     static_dir: public
