env: flex
runtime: nodejs
service: default

manual_scaling:
   instances: 1
resources:
   cpu: 1
   memory_gb: 0.5
   disk_size_gb: 10

handlers:
   - url: /api/.*
     script: auto
   - url: .*/favicon.png
     static_files: public/favicon.png
     upload: public/favicon.png
   - url: /static
     static_dir: public/static
   - url: /(.*\.(json|ico|js))$
     static_files: public/\1
     upload: public/.*\.(json|ico|js)$
   - url: .*
     static_files: public/index.html
     upload: public/index.html
     secure: always
     redirect_http_response_code: 301
